###

@path=http://localhost:8080

###
### ----------- Importation des events JSON to BDD -----------
###

GET {{path}}/import-events

###

GET {{path}}/import-events-fast

###
### ----------- Importation des users CSV to BDD -----------
###

GET {{path}}/import-users

###

GET {{path}}/import-users/synchronized

###

GET {{path}}/import-users/partitioned

###
### ----------- Exportation d'events en CSV -----------
###

GET {{path}}/export-events/simple

###

GET {{path}}/export-events/csv-by-id

###

GET {{path}}/export-events/csv-by-year

###
### ----------- Job History -----------
###

GET {{path}}/job-history/importUserJob

###

GET {{path}}/job-history/partitionedImportUserJob

###

GET {{path}}/job-history/exportEventsPartitionedJob
