spring:
  application:
    name: events-batch
  profiles:
    active:
      - dev
  datasource:
    # url: "jdbc:h2:mem:events-batch"
    # driver-class-name: org.h2.Driver
    # username: sa
    # password: ""
    url: "jdbc:postgresql://localhost:5432/events-batch"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: samsamsam
  sql:
    init:
      mode: always

  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: false
      path: /h2-console

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
